# .github/workflows/build.yml

name: Build (and publish tagged commits)
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Build
        run: dotnet build --configuration Release Geode

      - name: Upload class library artifact
        uses: actions/upload-artifact@v2
        with:
          name: Geode.dll
          path: Geode/bin/Release/netstandard2.0/Geode.dll

      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Geode/Geode.csproj
          PACKAGE_NAME: G-Earth-Geode
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # Symbols publishing currently broken with rohith/publish-nuget@v2
          # INCLUDE_SYMBOLS: true
